export enum Configuration {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  DB_NAME = 'DB_NAME',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_LOGGING = 'DB_LOGGING',
  JWT_SECRET = 'JWT_SECRET',
}
